- name: proxmox-templates.yml
  hosts: proxmox-01.home.local
  gather_facts: true
  vars_prompt: 
  - name: "ansible_password"
    prompt: "Enter the remote password"
    private: yes
  vars: 
    ansible_user: root
  tasks:
  - import_role: 
      name: proxmox-templates